parameters:
- name: ServerName
  type: string
- name: PublishTarget
  type: string
- name: IncludeNative
  type: boolean
- name: IsTestPipeline
  type: boolean

jobs:
- job: Initialize
  timeoutInMinutes: 90
  steps:
  - checkout: self
    fetchDepth: 0

  - task: UseDotNet@2
    displayName: "Use .NET SDK from global.json"
    retryCountOnTaskFailure: 3
    inputs:
      useGlobalJson: true

  - pwsh: |
      Write-Host "Attaching build reason string to the build for additional tag generation."
      @('$(Build.Reason)') | ConvertTo-Json -AsArray | Out-File -FilePath $(System.DefaultWorkingDirectory)/build-reason.json -Encoding utf8
      Write-Host '##vso[task.addattachment type=AdditionalTags;name=AdditionalTags;]$(System.DefaultWorkingDirectory)/build-reason.json'
    displayName: Tag build reason

  - task: Powershell@2
    displayName: "With pwsh true"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/Use-Common.ps1

  - task: Powershell@2
    displayName: "Without"
    inputs:
      filePath: $(Build.SourcesDirectory)/Use-Common.ps1