parameters:
- name: ServerName
  type: string
- name: PublishTarget
  type: string
- name: IncludeNative
  type: boolean
- name: IsTestPipeline
  type: boolean

jobs:
- job: Initialize
  timeoutInMinutes: 90
  steps:
  - checkout: self
    fetchDepth: 0

  - task: Powershell@2
    displayName: "Without"
    inputs:
      filePath: $(Build.SourcesDirectory)/Use-Common.ps1